/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MyMarquee {
      'dir': string;
    }
  }

  interface HTMLMyMarqueeElement extends StencilComponents.MyMarquee, HTMLStencilElement {}

  var HTMLMyMarqueeElement: {
    prototype: HTMLMyMarqueeElement;
    new (): HTMLMyMarqueeElement;
  };
  interface HTMLElementTagNameMap {
    'my-marquee': HTMLMyMarqueeElement;
  }
  interface ElementTagNameMap {
    'my-marquee': HTMLMyMarqueeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-marquee': JSXElements.MyMarqueeAttributes;
    }
  }
  namespace JSXElements {
    export interface MyMarqueeAttributes extends HTMLAttributes {
      'dir'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;